### ISSUE TITLE
Issue with intallation  Cytofkit2

### ISSUE THREAD

**Issue by AGGAGGAGG** [JinmiaoChenLab/cytofkit2#4]
Hello,

I tried to install cytofkit2 but I can't.

I have these Following lines:

> devtools::install_github("JinmiaoChenLab/cytofkit2")
Downloading GitHub repo JinmiaoChenLab/cytofkit2@master
These packages have more recent versions available.
Which would you like to update?

1:   XML (3.98-1.18 -> 3.98-1.19) [CRAN]

Enter one or more numbers separated by spaces, or an empty line to cancel
1: 1
XML (3.98-1.18 -> 3.98-1.19) [CRAN]
Installing 1 packages: XML

  There is a binary version available but the source version is later:
       binary    source needs_compilation
XML 3.98-1.18 3.98-1.19              TRUE

installing the source package ‘XML’

trying URL 'https://cran.rstudio.com/src/contrib/XML_3.98-1.19.tar.gz'
Content type 'application/x-gzip' length 1600788 bytes (1.5 MB)
downloaded 1.5 MB

* installing *source* package 'XML' ...
** package 'XML' correctement décompressé et sommes MD5 vérifiées
** libs
C:/RBuildTools/3.5/mingw_64/bin/gcc  -I"C:/Users/aggou/Desktop/R-35~1.2/include" -DNDEBUG -I/include/libxml2 -I/include -D_R_=1 -DUSE_R=1 -DUSE_XML_VERSION_H=1 -DLIBXML -DUSE_EXTERNAL_SUBSET=1 -DROOT_HAS_DTD_NODE=1 -DUMP_WITH_ENCODING=1 -DXML_ELEMENT_ETYPE=1  -DXML_ATTRIBUTE_ATYPE=1 -DLIBXML2=1 -DHAVE_XML_HAS_FEATURE -DLIBXML_STATIC         -O2 -Wall  -std=gnu99 -mtune=generic -c DocParse.c -o DocParse.o
In file included from DocParse.c:10:0:
DocParse.h:18:27: fatal error: libxml/parser.h: No such file or directory
 #include <libxml/parser.h>
                           ^
compilation terminated.
make: *** [C:/Users/aggou/Desktop/R-35~1.2/etc/x64/Makeconf:208: DocParse.o] Error 1
ERROR: compilation failed for package 'XML'
* removing 'C:/Users/aggou/Desktop/R-3.5.2/library/XML'
* restoring previous 'C:/Users/aggou/Desktop/R-3.5.2/library/XML'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘XML’ had non-zero exit status

Could you help me to fixe it?

Thanks
Anne

**Comment by SamGG** [comment]
Hi Anne,
I think you should better not update packages from source. Simply reply that you don't want to update the XML package, and this will probably work.
Best.

**Comment by siuhongh** [comment]
I have this error message:

Error: (converted from warning) cannot remove prior installation of package ‘BiocParallel’

Would you please help?  Thanks.

**Comment by SamGG** [comment]
Hi,
This message tells you that this package is in use on your computer.
When installing any package, it's better to start with an empty environment, meaning no data and no packages loaded. In fact, packages are automatically loaded if an object is depending on it. For example, a flowFrame is an object/concept of the flowCore package, thus flowCore is loaded if a flowFrame is defined is the environment/variables of the R session. Moreover, if you have multiple R/RStudio opened at the same, one of them could use and lock a package (or a dependency) you want to update.
So for  installing a package, you should at least "Restart R" from the "Session" menu of RStudio. This should allow you to install packages and preserving your data.
But I prefer to close ALL my RStudio projects and sessions, reopen RStudio, start a new empty project (new directory but not opening a new session) and then install whatever I need.
HTH

**Comment by jinmiaochen** [comment]
Many thanks to Samuel for helping us!

**Comment by CNicholasMDA** [comment]
* installing *source* package ‘data.table’ ...
** package ‘data.table’ successfully unpacked and MD5 sums checked
** libs
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG   -I/usr/local/include  -fopenmp -fPIC  -Wall -g -O2  -c assign.c -o assign.o
clang: error: unsupported option '-fopenmp'
make: *** [assign.o] Error 1
ERROR: compilation failed for package ‘data.table’
* removing ‘/Users/cnicholas/Library/R/3.4/library/data.table’
* restoring previous ‘/Users/cnicholas/Library/R/3.4/library/data.table’
Error: Failed to install 'cytofkit2' from GitHub:
  (converted from warning) installation of package ‘data.table’ had non-zero exit status
> 

**Hi Dr Chen and colleagues: does cytofkit2 work on R 3.4?**

**Comment by CNicholasMDA** [comment]
whoops.  it seems more like I am having trouble downloading the tarball from GitHub, for use in the MacOS environment.  I get this error:

Error: Failed to install 'cytofkit2' from GitHub:
  (converted from warning) installation of package ‘/var/folders/f3/jkp9k3117ds4qqzmmf0s_5tsrf6_s6/T//Rtmp5HsOpr/file17a93dcb6651/cytofkit2_2.0.1.tar.gz’ had non-zero exit status


Any thoughts?

**Comment by SamGG** [comment]
Hi courtney,
Make it clear whether data.table is correctly installed (run `library(data.table)`)
Report the exact command line you typed
R3.4 is quite old; I have just left out R3.5.3 for the current R3.6.1
Best

**Comment by CNicholasMDA** [comment]
Hi Sam.  thank you.
This is my input and output:

> library(data.table)
data.table 1.11.8  Latest news: r-datatable.com

**Comment by SamGG** [comment]
Fine. Retry installation of cytofkit2.

**Comment by CNicholasMDA** [comment]
I think it has to do with my R version. I'll probably update my R version and try again.
Thanks Sam!

clang: error: unsupported option '-fopenmp'
make: *** [assign.o] Error 1
ERROR: compilation failed for package ‘data.table’
* **removing ‘/Users/cnicholas/Library/R/3.4/library/data.table’
* restoring previous ‘/Users/cnicholas/Library/R/3.4/library/data.table’**
Error: Failed to install 'cytofkit2' from GitHub:
  (converted from warning) installation of package ‘data.table’ had non-zero exit status

**Comment by SamGG** [comment]
Probably. I am working on Windows.

**Comment by whitneytamaki** [comment]
Hello, 

when trying to install cytofkit2 i get the error: 

installing to /Library/Frameworks/R.framework/Versions/3.6/Resources/library/00LOCK-cytofkit2/00new/cytofkit2/libs
** R
** inst
** byte-compile and prepare package for lazy loading
**Error: object ‘getCompensationObj’ is not exported by 'namespace:flowWorkspace'
Execution halted
ERROR: lazy loading failed for package ‘cytofkit2’**
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/cytofkit2’
Error: Failed to install 'cytofkit2' from GitHub:
  (converted from warning) installation of package ‘/var/folders/jc/22gdwrpd5h7_lnzmhm2wthm40000gn/T//RtmpH3fLOX/file2a5d27e7fe54/cytofkit2_2.0.1.tar.gz’ had non-zero exit status





I have manually installed flowWorkspace, flowUtils, FlowSOM, and flowCorer packages because I was getting errors from those previously. 

Please advise on how to navigate this error! thanks!

**Comment by whitneyt1** [comment]
Hello,

I was working in R 3.6.1 because there was supposedly a dependency on that R version, but it wrecked some other programs I was using. So, I reinstalled R 3.5.2 to continue working on other things, and then cytofkit2 was able to be installed.

So my issue has been circumnavigated! 

Thanks.

**Comment by s2127542** [comment]
Hello, 

I am struggling to install and load the GUI. I have followed all the steps on the front page. 
It seems to work ok running the first installation steps. But then doesn't recognise cytofkit2 or the dashboard when running this section: 
```
library("cytofkit2")
cytofkit_shiny_dashboard()
```

Please can someone advise me on this? 

Thank you.
